# config/multifile/shavak/settings.py
# System definition for shavak
# Generated by continusbench add-system on 2026-06-09T14:51:03.369589

import os

site_configuration = {
    'systems': [
        {
            'name': 'shavak',
            'descr': 'single desktop system',
            'hostnames': ['.*'],
            'modules_system': 'spack',
            'resourcesdir': '/home/apps/hpc_inputs/',
            'stagedir': '/home/$USER/reframe/stage',
            'outputdir': '/home/$USER/reframe/output',
            'partitions': [
                {
                    'name': 'cpu',
                    'descr': 'CPU compute nodes',
                    'extras': {'lfs_available': False},
                    'scheduler': 'slurm',
                    'launcher': 'local',
                    'access': ['--partition=cpu'],
                    'environs': ['gnu', 'intel'],
                    'max_jobs': 100,
                    'devices': [
                        {
                            'type': 'nic',
                            'arch': 'ethernet',
                            'model': 'Intel Ethernet Connection X722',
                            'num_devices': 4
                        },
                        {
                            'type': 'memory',
                            'arch': 'ddr5',
                            'model': 'DDR5-4800',
                            'num_devices': 4
                        },
                        {
                            'type': 'infiniband',
                            'arch': 'hdr',
                            'model': 'HDR200',
                            'num_devices': 1
                        },
                    ],
                    'processor': {
                        'num_cpus': 48,
                        'num_sockets': 2,
                        'num_cpus_per_socket': 24,
                    },
                    'resources': [
                        {
                            'name': 'memory',
                            'options': ['--mem={size}', '--time=10:00:00'],
                        }
                    ],
                },
                {
                    'name': 'gpu',
                    'descr': 'GPU nodes — NVIDIA',
                    'extras': {'lfs_available': True},
                    'modules': ['cuda@12.5.1/klbpcme'],
                    'scheduler': 'slurm',
                    'launcher': 'local',
                    'access': ['--partition=gpu', '--gres=gpu:2', '--time=10:00:00'],
                    'environs': ['gnu', 'nvhpc'],
                    'max_jobs': 100,
                    'features': ['gpu', 'cuda'],
                    'devices': [
                        {
                            'type': 'gpu',
                            'arch': 'c80',
                            'model': 'Nvidia A100',
                            'num_devices': 2
                        },
                        {
                            'type': 'nic',
                            'arch': 'ethernet',
                            'model': 'Intel Ethernet Connection X722',
                            'num_devices': 4
                        },
                        {
                            'type': 'memory',
                            'arch': 'ddr5',
                            'model': 'DDR5-4800',
                            'num_devices': 4
                        },
                        {
                            'type': 'infiniband',
                            'arch': 'hdr',
                            'model': 'HDR200',
                            'num_devices': 1
                        },
                    ],
                    'processor': {
                        'num_cpus': 48,
                        'num_sockets': 2,
                        'num_cpus_per_socket': 24,
                    },
                    'resources': [
                        {
                            'name': 'memory',
                            'options': ['--mem={size}'],
                        }
                    ],
                },
            ],
        },
    ],
}
