import os
from datetime import datetime

import questionary
import yaml


# ---------------------------------------------------------------------------
# Template pieces – mirroring the paramrudra/settings.py structure exactly
# ---------------------------------------------------------------------------

_DEVICE_BLOCK = """\
                        {{
                            'type': '{dtype}',
                            'arch': '{arch}',
                            'model': '{model}',
                            'num_devices': {num_devices}
                        }},"""

_PROCESSOR_BLOCK = """\
                    'processor': {{
                        'num_cpus': {num_cpus},
                        'num_sockets': {num_sockets},
                        'num_cpus_per_socket': {num_cpus_per_socket},
                    }},"""

_RESOURCES_BLOCK_MEMORY = """\
                    'resources': [
                        {{
                            'name': 'memory',
                            'options': ['--mem={{size}}', '--time=10:00:00'],
                        }}
                    ],"""

_RESOURCES_BLOCK_GPU = """\
                    'resources': [
                        {{
                            'name': 'memory',
                            'options': ['--mem={{size}}'],
                        }}
                    ],"""

_PARTITION_TEMPLATE = """\
                {{
                    'name': '{pname}',
                    'descr': '{pdescr}',{extras_line}{modules_line}{scheduler_line}
                    'launcher': '{launcher}',{access_line}{environs_line}{max_jobs_line}{features_line}{devices_block}{processor_block}{resources_block}
                }},"""

_SYSTEM_TEMPLATE = """\
# config/multifile/{sysname}/settings.py
# System definition for {sysname}
# Generated by continusbench add-system on {generated_at}

import os

site_configuration = {{
    'systems': [
        {{
            'name': '{sysname}',
            'descr': '{description}',
            'hostnames': ['.*'],
            'modules_system': 'spack',
            'resourcesdir': '{resourcesdir}',
            'stagedir': '{stagedir}',
            'outputdir': '{outputdir}',
            'partitions': [
{partitions}
            ],
        }},
    ],
}}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ask_int(prompt, default):
    raw = questionary.text(prompt, default=str(default)).ask()
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def _collect_devices(pname, ptype):
    """Interactively collect device entries for a partition."""
    devices = []

    # GPU – only relevant for gpu partitions (but allow on others too)
    want_gpu = ptype == "gpu"
    if not want_gpu:
        want_gpu = questionary.confirm(
            f"  Add GPU device to '{pname}'?", default=False
        ).ask()
    if want_gpu:
        arch  = questionary.text("  GPU arch (e.g. c80, a100):", default="c80").ask() or "c80"
        model = questionary.text("  GPU model (e.g. Nvidia A100):", default="Nvidia A100").ask() or "Nvidia A100"
        num   = _ask_int("  Number of GPU devices:", 2)
        devices.append({"type": "gpu", "arch": arch, "model": model, "num_devices": num})

    # NIC
    if questionary.confirm(f"  Add NIC device to '{pname}'?", default=True).ask():
        arch  = questionary.text("  NIC arch (e.g. ethernet, infiniband):", default="ethernet").ask() or "ethernet"
        model = questionary.text("  NIC model:", default="Intel Ethernet Connection X722").ask()
        num   = _ask_int("  Number of NICs:", 4)
        devices.append({"type": "nic", "arch": arch, "model": model, "num_devices": num})

    # Memory/NUMA
    if questionary.confirm(f"  Add Memory/NUMA device to '{pname}'?", default=True).ask():
        arch  = questionary.text("  Memory arch (e.g. ddr5, ddr4):", default="ddr5").ask() or "ddr5"
        model = questionary.text("  Memory model (e.g. DDR5-4800):", default="DDR5-4800").ask()
        num   = _ask_int("  Number of NUMA nodes:", 4)
        devices.append({"type": "memory", "arch": arch, "model": model, "num_devices": num})

    # InfiniBand
    if questionary.confirm(f"  Add InfiniBand device to '{pname}'?", default=True).ask():
        arch  = questionary.text("  IB arch (e.g. hdr, edr):", default="hdr").ask() or "hdr"
        model = questionary.text("  IB model (e.g. HDR200):", default="HDR200").ask()
        num   = _ask_int("  Number of IB devices:", 1)
        devices.append({"type": "infiniband", "arch": arch, "model": model, "num_devices": num})

    return devices


def _collect_processor():
    num_cpus         = _ask_int("  Total CPUs per node:", 48)
    num_sockets      = _ask_int("  Number of sockets:", 2)
    num_cpus_per_socket = _ask_int("  CPUs per socket:", num_cpus // max(1, 2))
    return {
        "num_cpus": num_cpus,
        "num_sockets": num_sockets,
        "num_cpus_per_socket": num_cpus_per_socket,
    }


def _render_partition(p):
    """Turn a partition dict into a formatted Python literal string."""
    pname   = p["name"]
    ptype   = p["type"]
    sched   = p["scheduler"]
    launcher = "local" if sched == "local" else "local"  # most clusters use mpirun at job level

    # descr
    descr_map = {
        "login": "Login node — local execution",
        "cpu":   "CPU compute nodes",
        "gpu":   "GPU nodes — NVIDIA",
        "hm":    "High-memory nodes",
    }
    pdescr = descr_map.get(ptype, f"{ptype} partition")

    # extras
    lfs = ptype == "gpu"
    extras_line = f"\n                    'extras': {{'lfs_available': {lfs}}},"

    # modules (gpu only by default)
    modules_line = ""
    if ptype == "gpu" and p.get("cuda_module"):
        modules_line = f"\n                    'modules': ['{p['cuda_module']}'],"

    # scheduler
    scheduler_line = f"\n                    'scheduler': '{sched}',"

    # access
    access_line = ""
    if sched != "local":
        access_parts = [f"'--partition={pname}'"]
        if ptype == "gpu":
            ngpu = next(
                (d["num_devices"] for d in p.get("devices", []) if d["type"] == "gpu"), 2
            )
            access_parts += [f"'--gres=gpu:{ngpu}'", "'--time=10:00:00'"]
        access_line = "\n                    'access': [" + ", ".join(access_parts) + "],"

    # environs
    env_map = {
        "login": ["gnu", "intel", "foss"],
        "cpu":   ["gnu", "foss", "intel"],
        "hm":    ["gnu", "intel"],
        "gpu":   ["gnu", "foss", "nvhpc"],
    }
    environs = env_map.get(ptype, ["gnu"])
    environs_line = "\n                    'environs': [" + ", ".join(f"'{e}'" for e in environs) + "],"

    # max_jobs
    max_jobs_line = ""
    if sched != "local":
        max_jobs_line = "\n                    'max_jobs': 100,"

    # features (gpu only)
    features_line = ""
    if ptype == "gpu":
        features_line = "\n                    'features': ['gpu', 'cuda'],"

    # devices block
    devices_block = ""
    if p.get("devices"):
        device_lines = "\n".join(
            _DEVICE_BLOCK.format(
                dtype=d["type"], arch=d["arch"],
                model=d["model"], num_devices=d["num_devices"]
            )
            for d in p["devices"]
        )
        devices_block = f"\n                    'devices': [\n{device_lines}\n                    ],"

    # processor block
    processor_block = ""
    if p.get("processor") and sched != "local":
        proc = p["processor"]
        processor_block = "\n" + _PROCESSOR_BLOCK.format(**proc)

    # resources block – handled via placeholder below

    # resources_block contains literal {size} which must survive .format()
    # Use a placeholder and do a final substitution afterwards.
    _RESOURCES_MEMORY = (
        "\n                    'resources': [\n"
        "                        {\n"
        "                            'name': 'memory',\n"
        "                            'options': ['--mem={size}', '--time=10:00:00'],\n"
        "                        }\n"
        "                    ],"
    )
    _RESOURCES_GPU = (
        "\n                    'resources': [\n"
        "                        {\n"
        "                            'name': 'memory',\n"
        "                            'options': ['--mem={size}'],\n"
        "                        }\n"
        "                    ],"
    )

    resources_final = ""
    if sched != "local":
        resources_final = _RESOURCES_GPU if ptype == "gpu" else _RESOURCES_MEMORY

    result = _PARTITION_TEMPLATE.format(
        pname=pname,
        pdescr=pdescr,
        extras_line=extras_line,
        modules_line=modules_line,
        scheduler_line=scheduler_line,
        launcher=launcher,
        access_line=access_line,
        environs_line=environs_line,
        max_jobs_line=max_jobs_line,
        features_line=features_line,
        devices_block=devices_block,
        processor_block=processor_block,
        resources_block="__RESOURCES__",
    )
    return result.replace("__RESOURCES__", resources_final)


# ---------------------------------------------------------------------------
# Main generator class
# ---------------------------------------------------------------------------

class SystemGenerator:
    def __init__(self, config_dir=None):
        # Root folder that holds one sub-folder per system
        self.config_dir = config_dir or os.path.join(
            os.path.dirname(__file__), '..', '..', 'config', 'systems'
        )
        os.makedirs(self.config_dir, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def interactive_onboard(self):
        """Run the full interactive wizard and write config files."""

        print("\n=== continusbench: Add New System ===\n")

        # --- Basic system info ---
        name = questionary.text("System name (e.g. supermuc, paramrudra):").ask()
        if not name:
            return None

        description = questionary.text("Short description:").ask() or ""
        resourcesdir = (
            questionary.text(
                "Resources directory (input data, modules, etc.):",
                default="/home/apps/hpc_inputs/",
            ).ask()
            or "/home/apps/hpc_inputs/"
        )
        stagedir = (
            questionary.text(
                "Stage directory:",
                default="/scratch/$USER/reframe/stage",
            ).ask()
            or "/scratch/$USER/reframe/stage"
        )
        outputdir = (
            questionary.text(
                "Output directory:",
                default="/scratch/$USER/reframe/output",
            ).ask()
            or "/scratch/$USER/reframe/output"
        )

        # --- Partitions ---
        partitions = []
        print("\n--- Partitions (leave name empty to finish) ---")
        while True:
            pname = questionary.text("Partition name:").ask()
            if not pname:
                break

            ptype = questionary.select(
                f"  Type of '{pname}':",
                choices=["login", "cpu", "gpu", "hm"],
            ).ask()

            scheduler = questionary.select(
                f"  Scheduler for '{pname}':",
                choices=["slurm", "pbs", "local"],
            ).ask()

            # CUDA module for GPU partitions
            cuda_module = ""
            if ptype == "gpu":
                cuda_module = (
                    questionary.text(
                        "  CUDA spack module string (e.g. cuda@12.5.1/klbpcme):",
                        default="cuda@12.5.1/klbpcme",
                    ).ask()
                    or ""
                )

            # Devices
            print(f"\n  --- Devices for partition '{pname}' ---")
            devices = _collect_devices(pname, ptype)

            # Processor
            processor = None
            if scheduler != "local":
                print(f"\n  --- Processor info for '{pname}' ---")
                processor = _collect_processor()

            partitions.append(
                {
                    "name": pname,
                    "type": ptype,
                    "scheduler": scheduler,
                    "cuda_module": cuda_module,
                    "devices": devices,
                    "processor": processor,
                }
            )
            print()

        if not partitions:
            partitions.append(
                {
                    "name": "default",
                    "type": "cpu",
                    "scheduler": "local",
                    "cuda_module": "",
                    "devices": [],
                    "processor": None,
                }
            )

        config = {
            "name": name,
            "description": description,
            "resourcesdir": resourcesdir,
            "stagedir": stagedir,
            "outputdir": outputdir,
            "generated_at": datetime.now().isoformat(),
            "partitions": partitions,
        }

        # Write files
        system_dir, yaml_path = self._write_files(config)
        print(f"\n✓  YAML metadata  → {yaml_path}")
        print(f"✓  ReFrame config → {os.path.join(system_dir, 'settings.py')}")
        return yaml_path

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _write_files(self, config):
        name = config["name"]

        # One folder per system: config/systems/<name>/
        system_dir = os.path.join(self.config_dir, name)
        os.makedirs(system_dir, exist_ok=True)

        # 1. YAML metadata
        yaml_path = os.path.join(system_dir, f"{name}.yaml")
        with open(yaml_path, "w") as fh:
            yaml.dump(config, fh, default_flow_style=False, sort_keys=False)

        # 2. ReFrame settings.py
        self._generate_reframe_config(system_dir, config)

        return system_dir, yaml_path

    def _generate_reframe_config(self, system_dir, config):
        partition_blocks = [_render_partition(p) for p in config["partitions"]]
        partitions_text  = "\n".join(partition_blocks)

        content = _SYSTEM_TEMPLATE.format(
            sysname      = config["name"],
            description  = config["description"],
            resourcesdir = config["resourcesdir"],
            stagedir     = config["stagedir"],
            outputdir    = config["outputdir"],
            generated_at = config["generated_at"],
            partitions   = partitions_text,
        )

        settings_path = os.path.join(system_dir, "settings.py")
        with open(settings_path, "w") as fh:
            fh.write(content)

    # ------------------------------------------------------------------

    def load_system(self, name):
        filepath = os.path.join(self.config_dir, name, f"{name}.yaml")
        if not os.path.exists(filepath):
            return None
        with open(filepath) as fh:
            return yaml.safe_load(fh)