name: ReFrame Test Suite

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  reframe-tests:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Set ReFrame Environment
      run: |
        export RFM_CONFIG_FILES="${PWD}/config/common/settings.py:${PWD}/config/environments/settings.py:${PWD}/config/pseudo-cluster/settings.py"
        export RFM_CHECK_SEARCH_PATH="${PWD}"
        export RFM_CHECK_SEARCH_RECURSIVE=yes
        export RFM_GENERATE_FILE_REPORTS=true

        echo ">>> Diagnostics"
        which reframe
        reframe --version

        echo ">>> Run ReFrame tests"
        reframe -c basics/hello/hello1.py -r

  reframe-openmp:
    name: ReFrame OpenMP / GPU Tests
    needs: reframe-tests
    runs-on: [self-hosted]
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
            pip install -e .

        - name: Run GPU Tests
          run: |
            export RFM_CONFIG_FILES="${PWD}/config/common/settings.py:${PWD}/config/environments/settings.py:${PWD}/config/pseudo-cluster/settings.py"
            export RFM_CHECK_SEARCH_PATH="${PWD}"
            export RFM_CHECK_SEARCH_RECURSIVE=yes
            reframe -n 'osu_build_run.*benchmark_info=mpi.collective.osu_allreduce.*build_type=cuda' \
              -S device_buffers=cuda \
              -S num_tasks=16 \
              -S valid_systems=paramrudra.snbose:gpu \
              -S valid_prog_environs=gnu \
              -l
